---
title: Ermita San Frutos
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: "San Frutos nace en ..."
author: Ermita San Frutos
image: images/san-frutos.webp
icon: img/favicon.ico
openingHours: Sa 11:30-20:30, Su 11:30-18:00
phone: 921 52 92 28
email: seminario@iglesianavarra.org
address: 40331 Burgomillodo, Segovia
bizum: BIZUM
googleMaps: https://maps.app.goo.gl/QHAcFKPbd6ibKvqQ9
facebook: fb.com/sanfrutosdelduraton
locale: es_ES
street: SN
city: Burgomillodo
region: Segovia
zip: 40331
country: España
latitude: 41.324731457087516
longitude: -3.878941271164452
ldType: Organization
analytics:
  google: 
  mode: privacy
keywords: segovia, ermita, san frutos, románico, romería, naturaleza, oración
baseurl: ''
url: https://ermitasanfrutos.diocesisdesegovia.es
modules:
- facade
- scrollDown
